services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://${PG_USER}:${PG_PASSWORD}@db:5432/${PG_DB}
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/app
    networks:
      - quantumpay-network

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - quantumpay-network

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data
    networks:
      - quantumpay-network

volumes:
  pgdata:
  redisdata:

networks:
  quantumpay-network:
    driver: bridge